version: 2

models:
  - name: fct_orders
    description: "The main fact table for e-commerce orders"
    columns:
      - name: order_id
        description: "Primary key for the order"
        tests:
          - unique
          - not_null

      - name: customer_id
        description: "Foreign key to the customer"
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id